<script>
    import { DefaultApi } from "$lib/generated"; // Import the autogenerated API code
    import { createEventDispatcher } from "svelte";

    const dispatch = createEventDispatcher();
    /**
     * @type {File | null}
     */
    let selectedFile = null;

    /**
     * @type {string | null}
     */
    let fileId = null;

    /**
     * @type {string | null}
     */
    let imageUrl = null;

    /**
     * @type {never[]}
     */
    let fileIds = [];
    const MAX_BOXES = 5;

    let boxes = Array.from({ length: MAX_BOXES }, () => ({
        selectedFile: null,
        fileId: null,
        imageUrl: null,
    }));

    const api = new DefaultApi();

    /**
     * @param {string | number} index
     */
    async function handleFileUpload(index) {
        console.log(index)
        const { selectedFile } = boxes[index];
        if (selectedFile) {
            try {
                const response = await api.uploadImagePost({
                    file: selectedFile,
                });
                boxes[index].fileId = response;
                fileIds[index] = response;
                dispatch("list",fileIds);
                console.log(response)
            } catch (error) {
                console.error("Error uploading image:", error);
            }
        }
    }

    /**
     * @param {{target: {files: FileList;};}} event
     * @param {string | number} index
     */
    function handleFileChange(index, event) {
        const selectedFile = event.target.files[0];
        const imageUrl = URL.createObjectURL(selectedFile);
        boxes[index] = { selectedFile, imageUrl, fileId: null };
    }

    /**
     * @param {string | number} index
     */
    function removeImage(index) {
        boxes[index] = { selectedFile: null, imageUrl: null, fileId: null };
    }

    async function handleSubmit() {
        for (let i = 0; i < MAX_BOXES; i++) {
            console.log(i)
            await handleFileUpload(i);
        }
    }

    export { handleSubmit };

    dispatch("list", fileIds);
</script>

<div class="box-container">
    {#each boxes as box, index (index)}
        <div class="box">
            <input
                class="input-taker"
                type="file"
                accept="image/*"
                on:change={() => handleFileChange(index, event)}
            />
            {#if box.imageUrl}
                <div class="image-container">
                    <img src={box.imageUrl} alt="Selected Image" />
                    <button on:click={() => removeImage(index)}>Remove</button>
                </div>
            {/if}
        </div>
    {/each}
</div>

{#if fileId}
    <p>File uploaded successfully. File ID: {fileId}</p>
{/if}

<style>
    .box-container {
        display: flex;
        justify-content: space-around;
        align-items: center;
        flex-wrap: wrap;
        height: 100vh;
    }
    .box {
        position: relative;
        width: 30vw;
        height: 40vh;
        margin: 2rem;
        border: 1px solid black;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    .image-container {
        position: relative;
        width: 90%;
        height: 90%;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    img {
        max-width: 100%;
        max-height: 100%;
        object-fit: contain;
        z-index: 0;
        border: 2px greenyellow solid;
    }
    button {
        z-index: 100;
        position: absolute;
        bottom: 0;
        right: 0;
    }
</style>
