openapi: 3.0.0
info:
    title: CCMS
    description: |
        This API is used for communication between CCMS (Campus Complaint Management System) server and client.
    version: 0.0.1
paths:
    /login:
        post:
            summary: Login to user account
            description: Get username and password and authenticate the user.
                Returns sessionId for further requests
            operationId: login
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - password
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
                required: true
            responses:
                "200":
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                type: string
                "403":
                    description: "Forbidden"

    /announcements:
        $ref: './paths/announcements.yaml'


servers:
    - url: http://13.233.99.87:8080
