openapi: 3.0.0
info:
    title: CCMS
    description: |
        This API is used for communication between CCMS (Campus Complaint Management System) server and client.
    version: 0.0.2
paths:
    /auth/login:
        $ref: "./paths/login.yaml"

    /announcements:
        $ref: "./paths/announcements.yaml"

    /complain_overview:
        $ref: "./paths/complain_overview.yaml"

    /submit_complain:
        $ref: "./paths/submit_complaint.yaml"

    /usersDetail:
        $ref: "./paths/users_detail.yaml"

    /userDetailUpdate:
        $ref: "./paths/user_detail_update.yaml"

    /getComplaintInfo/{id}:
        $ref: "./paths/get_complaint_info.yaml"


    /upload/image:
        post:
            operationId: uploadFile
            summary: Upload Image
            description: |
                Uploads an image and returns its corresponding file ID.
            requestBody:
                required: true
                content:
                    image/*:
                        schema:
                            type: string
                            format: binary
            responses:
                '200':
                    description: Successful response
                    content:
                        text/plain:
                            schema:
                                type: string
                                minLength: 40
                                maxLength: 40
                '400':
                    description: Bad request
                '500':
                    description: Internal server error

#    /download/image/{fileId}:
#        get:
#            operationId: downloadFile
#            summary: Download Image
#            description: |
#                Downloads the image corresponding to the provided file ID.
#            parameters:
#                - in: path
#                  name: fileId
#                  required: true
#                  description: The ID of the file to download
#                  schema:
#                      type: string
#            responses:
#                "200":
#                    content:
#                        multipart/form-data:
#                            schema:
#                                type: object
#                                properties:
#                                    image:
#                                        format: binary
#                                        type: string
#                    description: Successful response
#                "404":
#                    description: File not found
#                "500":
#                    description: Internal server error


    /download/image/{fileId}:
        get:
            operationId: downloadFile
            summary: Download Image
            description: |
                Downloads the image corresponding to the provided file ID.
            parameters:
                -   in: path
                    name: fileId
                    required: true
                    description: The ID of the file to download
                    schema:
                        type: string
            responses:
                "200":
                    content:
                        image/*:
                            schema:
                                type: string
                                format: binary
                    description: Successful response
                "404":
                    description: File not found
                "500":
                    description: Internal server error



servers:
    -   url: http://localhost:8080
